name: Documentation Tests
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

jobs:
  doctest:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.13
          activate-environment: true

      - name: Install invoke
        run: |
          make install-invoke

      - name: Install packages
        run: |
          inv install --all-deps

      - name: Show python config
        run: |
          inv show-python-config

      - name: Show installed packages
        run: |
          inv show-installed-packages

      - name: Run doctest on source code
        run: |
          inv doctest-src

#  build:
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: '3.12'
#
#      - name: Install Poetry
#        uses: snok/install-poetry@v1
#
#      - name: Set environment variable
#        run: |
#          echo $(poetry run poetry env info --path)/bin >> $GITHUB_PATH
#
#      - name: Install packages
#        run: |
#          make install-all
#
#      - name: Setup doc deploy
#        env:
#          CI_BOT_EMAIL: ${{secrets.CI_BOT_EMAIL}}
#        run: |
#          git config --global user.name ci-docs-bot
#          git config --global user.email $CI_BOT_EMAIL
#
#      - name: Build documentation
#        run: |
#          mike deploy --config-file docs/mkdocs.yml --branch tmp-doc-build-1234 dev
