name: Update dependencies
on:
  schedule:
    - cron: "0 6 * * 6" # run every Saturday at 6:00 AM UTC
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: 3.13

      - name: Install invoke
        run: |
          make install-invoke

      - name: Install packages
        run: |
          inv update

      - name: Install packages
        run: |
          inv install --all-deps

      - name: Show python config
        run: |
          inv show-python-config

      - name: Show installed packages
        run: |
          inv show-installed-packages

      - name: Run unit tests
        run: |
          inv unit-test --cov

      - uses: peter-evans/create-pull-request@v7
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/dependencies
          title: Update dependencies
          commit-message: "Update dependencies"
          body: Update dependencies to latest compatible version.
          author: ci-bot <${{secrets.CI_BOT_EMAIL}}>

      - name: Trigger CI workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/ci.yml/dispatches \
            -d '{"ref":"main", "inputs": {"branch": "update/dependencies"}}'
